version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building the React app"
      - npm run build
  post_build:
    commands:
      - echo "Deploying to S3"
      - aws s3 sync build/ s3://my-react-app-demo-2025 --delete

artifacts:
  files:
    - '**/*'
  base-directory: build/